#include "variant.h"

//Tim's Variants for Quail

const PinDescription g_APinDescription[]=
{
  //0 NULL PIN
  { PORTB, 0, PIO_NOT_A_PIN, PIN_ATTR_PWM_G, No_ADC_Channel, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_NONE },
  //1-4 LEDs
  { PORTB, 16, PIO_DIGITAL, (PIN_ATTR_DIGITAL|PIN_ATTR_PWM_F), No_ADC_Channel, TCC3_CH0, NOT_ON_TIMER, EXTERNAL_INT_0 },
  { PORTB, 17, PIO_DIGITAL, PIN_ATTR_DIGITAL, No_ADC_Channel, TCC3_CH1, NOT_ON_TIMER, EXTERNAL_INT_1 },
  { PORTB, 18, PIO_DIGITAL, PIN_ATTR_DIGITAL, No_ADC_Channel, TCC1_CH0, NOT_ON_TIMER, EXTERNAL_INT_2 },
  { PORTB, 19, PIO_DIGITAL, PIN_ATTR_DIGITAL, No_ADC_Channel, TCC1_CH1, NOT_ON_TIMER, EXTERNAL_INT_3 },

  //5-9 ADC SPI and GPIO, SERCOM1, IOSET3
  { PORTB, 23, PIO_SERCOM, PIN_ATTR_DIGITAL, No_ADC_Channel, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_7 }, // MISO: SERCOM1/PAD[3], ALSO ADC READY PIN
  { PORTC, 28, PIO_SERCOM, PIN_ATTR_DIGITAL, No_ADC_Channel, NOT_ON_PWM, NOT_ON_TIMER, NOT_AN_INTERRUPT }, // SCK: SERCOM1/PAD[1]
  { PORTC, 27, PIO_SERCOM, PIN_ATTR_DIGITAL, No_ADC_Channel, NOT_ON_PWM, NOT_ON_TIMER, NOT_AN_INTERRUPT }, // MOSI: SERCOM1/PAD[0]
  { PORTB, 21, PIO_DIGITAL, PIN_ATTR_DIGITAL, No_ADC_Channel, NOT_ON_PWM, NOT_ON_TIMER, NOT_AN_INTERRUPT }, // CS
  { PORTA, 27, PIO_DIGITAL, PIN_ATTR_DIGITAL, No_ADC_Channel, NOT_ON_PWM, NOT_ON_TIMER, NOT_AN_INTERRUPT }, // ADC_SYNC

  //10-13 Radio SPI, SERCOM5, IOSET2
  { PORTA, 20, PIO_SERCOM, PIN_ATTR_DIGITAL, No_ADC_Channel, NOT_ON_PWM, NOT_ON_TIMER, NOT_AN_INTERRUPT }, // MISO: SERCOM5/PAD[2]
  { PORTA, 21, PIO_SERCOM, PIN_ATTR_DIGITAL, No_ADC_Channel, NOT_ON_PWM, NOT_ON_TIMER, NOT_AN_INTERRUPT }, // CS
  { PORTA, 22, PIO_SERCOM_ALT, PIN_ATTR_DIGITAL, No_ADC_Channel, NOT_ON_PWM, NOT_ON_TIMER, NOT_AN_INTERRUPT }, // SCK: SERCOM5/PAD[1]
  { PORTA, 23, PIO_SERCOM_ALT, PIN_ATTR_DIGITAL, No_ADC_Channel, NOT_ON_PWM, NOT_ON_TIMER, NOT_AN_INTERRUPT }, // MOSI: SERCOM5/PAD[0]
  //14-16 Radio GPIO
  { PORTC, 24, PIO_DIGITAL, PIN_ATTR_DIGITAL, No_ADC_Channel, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_8 }, // DIO1
  { PORTC, 25, PIO_DIGITAL, PIN_ATTR_DIGITAL, No_ADC_Channel, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_9 }, // BUSY
  { PORTC, 26, PIO_DIGITAL, PIN_ATTR_DIGITAL, No_ADC_Channel, NOT_ON_PWM, NOT_ON_TIMER, EXTERNAL_INT_10 }, // NRESET

  //17-21 Squib SPI and GPIO, SERCOM0, IOSET4
  { PORTC, 19, PIO_SERCOM_ALT, PIN_ATTR_DIGITAL, No_ADC_Channel, NOT_ON_PWM, NOT_ON_TIMER, NOT_AN_INTERRUPT }, // MISO: SERCOM0/PAD[3]
  { PORTC, 16, PIO_SERCOM_ALT, PIN_ATTR_DIGITAL, No_ADC_Channel, NOT_ON_PWM, NOT_ON_TIMER, NOT_AN_INTERRUPT }, // SCK: SERCOM0/PAD[1]
  { PORTC, 17, PIO_SERCOM_ALT, PIN_ATTR_DIGITAL, No_ADC_Channel, NOT_ON_PWM, NOT_ON_TIMER, NOT_AN_INTERRUPT }, // MOSI: SERCOM0/PAD[0]
  { PORTC, 18, PIO_DIGITAL, PIN_ATTR_DIGITAL, No_ADC_Channel, NOT_ON_PWM, NOT_ON_TIMER, NOT_AN_INTERRUPT }, // CS1
  { PORTC, 20, PIO_DIGITAL, PIN_ATTR_DIGITAL, No_ADC_Channel, NOT_ON_PWM, NOT_ON_TIMER, NOT_AN_INTERRUPT }, // CS2

  //22-29 Solenoid control NOT_AN_INTERRUPT
  { PORTC, 10, PIO_DIGITAL, (PIN_ATTR_DIGITAL|PIN_ATTR_PWM_F), No_ADC_Channel, TCC0_CH0, NOT_ON_TIMER, NOT_AN_INTERRUPT }, // SV1
  { PORTC, 11, PIO_DIGITAL, (PIN_ATTR_DIGITAL|PIN_ATTR_PWM_F), No_ADC_Channel, TCC0_CH1, NOT_ON_TIMER, NOT_AN_INTERRUPT }, // SV2
  { PORTC, 12, PIO_DIGITAL, (PIN_ATTR_DIGITAL|PIN_ATTR_PWM_F), No_ADC_Channel, TCC0_CH2, NOT_ON_TIMER, NOT_AN_INTERRUPT }, // SV3
  { PORTC, 13, PIO_DIGITAL, (PIN_ATTR_DIGITAL|PIN_ATTR_PWM_F), No_ADC_Channel, TCC0_CH3, NOT_ON_TIMER, NOT_AN_INTERRUPT }, // SV4
  { PORTC, 14, PIO_DIGITAL, (PIN_ATTR_DIGITAL|PIN_ATTR_PWM_F), No_ADC_Channel, TCC0_CH4, NOT_ON_TIMER, NOT_AN_INTERRUPT }, // SV5
  { PORTC, 15, PIO_DIGITAL, (PIN_ATTR_DIGITAL|PIN_ATTR_PWM_F), No_ADC_Channel, TCC0_CH5, NOT_ON_TIMER, NOT_AN_INTERRUPT }, // SV6
  { PORTC,  6, PIO_DIGITAL, (PIN_ATTR_DIGITAL|PIN_ATTR_PWM_F), No_ADC_Channel, NOT_ON_PWM, NOT_ON_TIMER, NOT_AN_INTERRUPT }, // SV7
  { PORTC,  7, PIO_DIGITAL, (PIN_ATTR_DIGITAL|PIN_ATTR_PWM_F), No_ADC_Channel, NOT_ON_PWM, NOT_ON_TIMER, NOT_AN_INTERRUPT }, // SV8
} ; 

const void* g_apTCInstances[TCC_INST_NUM+TC_INST_NUM]={ TCC0, TCC1, TCC2, TCC3, TCC4, TC0, TC1, TC2, TC3, TC4, TC5 } ;
const uint32_t GCLK_CLKCTRL_IDs[TCC_INST_NUM+TC_INST_NUM] = { TCC0_GCLK_ID, TCC1_GCLK_ID, TCC2_GCLK_ID, TCC3_GCLK_ID, TCC4_GCLK_ID, TC0_GCLK_ID, TC1_GCLK_ID, TC2_GCLK_ID, TC3_GCLK_ID, TC4_GCLK_ID, TC5_GCLK_ID } ;

SERCOM sercom0( SERCOM0 ) ;
SERCOM sercom1( SERCOM1 ) ;
SERCOM sercom2( SERCOM2 ) ;
SERCOM sercom3( SERCOM3 ) ;
SERCOM sercom4( SERCOM4 ) ;
SERCOM sercom5( SERCOM5 ) ;

//Uart GPSSerial(&sercom2, 20, 19, SERCOM_RX_PAD_1, UART_TX_PAD_0) ;

void SERCOM2_0_Handler()
{
  //GPSSerial.IrqHandler();
}
void SERCOM2_1_Handler()
{
  //GPSSerial.IrqHandler();
}
void SERCOM2_2_Handler()
{
  //GPSSerial.IrqHandler();
}
void SERCOM2_3_Handler()
{
  //GPSSerial.IrqHandler();
}