name: PlatformIO Builds
on: [push, pull_request]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        target:
              - guppy
              - salmon
              - quail
              - quail-ground
              - guppy-ground
              - dummy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
          fetch-depth: 0
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U platformio
      - name: Build examples
        run: |
          platformio run -e ${{ matrix.target }}
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.target }}.bin
          path: .pio/build/${{ matrix.target }}/firmware.bin
